name: train-test
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-dvc@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6' 
      - name: "Get my data"
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          # Pull the dataset from cloud storage
          dvc pull
          
          # Reproduce your pipeline
          pip install -r src/requirements.txt
          dvc repro
          
          # Push the resulting model to cloud storage
          dvc push --run-cache
