name: train-test
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-dvc@v1
      - name: "Get my data"
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          # Pull the dataset from cloud storage
          dvc pull data/data.xml
          
          # Reproduce your pipeline
          dvc repro
          
          # Push the resulting model to cloud storage
          dvc push model.pkl
